'use client'

import Link from 'next/link'
import { useMemo, useRef } from 'react'
import {
  USER_SEED as SHARED_USER_SEED,
  hashSeed as sharedHashSeed,
  userCuratedHue as sharedUserCuratedHue,
  buildPointMotionProfile as sharedBuildPointMotionProfile,
  generateAnimatedBlobPath as sharedGenerateAnimatedBlobPath,
  blobGradientStops,
  useBlobAnimation,
} from '@/lib/blobs'
import CtaButton from './CtaButton'
import ContinueLink from './ContinueLink'

// Phase 3 skeleton — reference/landing-redesign.md section 10. Copy below is
// taken verbatim from the ledger (sections 4a, 2, 3, 4, 5). Anywhere the
// ledger has no concrete text (tagged U, or a question with no drafted
// answer) renders a visible [PLACEHOLDER: ...] instead of invented copy.
// Skeleton fidelity only — no polish, no extra animation beyond the one
// hero blob.

const sans = 'var(--font-inter), -apple-system, sans-serif'
const serif = 'var(--font-newsreader), Georgia, serif'

// Ledger section 6 design rules: keep cream/charcoal/Newsreader/Inter/coral
// and the blob engine. Coral is #D85A30 per that section — a different value
// than the old (now-removed) LandingPageClient mkCoral (#F0A98A), used here
// deliberately because the ledger names this exact hex, not the old one.
const mkCream = '#F7F4ED'
const mkCard = '#EFEAE0'
const mkCharcoal = '#262420'
const mkCharcoalSoft = '#57534A'
const mkLine = 'rgba(38,36,32,0.1)'
const mkCoral = '#D85A30'

const BENEFIT_ROW = [
  'How you work',
  'How you connect',
  'What gives you energy',
  'Where you thrive',
  "Where you're headed",
]

const FAQ = [
  {
    q: 'Is it accurate?',
    a: null, // ledger: "P, write carefully" — no drafted answer text given
  },
  {
    q: 'Do I need an account?',
    a: "No, not for your first 5 patterns. You can optionally save progress with an email, and an account is needed at the paid unlock.",
  },
  {
    q: 'What does it cost?',
    a: 'EUR 49 one time after the free 5 patterns.',
  },
  {
    q: 'What happens to my data?',
    a: [
      'Your answers stay in your browser until you choose to save your progress or unlock.',
      "The written explanation of each pattern is generated by an AI model from the name of the trait, your result bucket (high, mid or low) and the trait word, not from your individual answers, and it is not sent your email.",
    ],
  },
  {
    q: 'Is this AI?',
    a: 'Your scores come from the same fixed questionnaire for everyone. The explanation of each pattern is written by AI from your scores.',
  },
  {
    q: 'How is this different from 16Personalities or a chat with AI?',
    a: null, // ledger: "P, factual comparisons only" — no drafted answer text given
  },
]

const css = `
  .hv2-wrap{max-width:720px;margin:0 auto;padding:0 24px;}
  .hv2-section{padding:56px 24px;}
  .hv2-section h2{font-family:'Newsreader',serif;font-size:28px;font-weight:500;line-height:1.25;margin:0 0 14px;text-align:center;}
  .hv2-body{font-size:15.5px;line-height:1.65;color:${mkCharcoalSoft};max-width:600px;margin:0 auto 14px;text-align:center;}

  .hv2-hero{padding:96px 24px 48px;text-align:center;}
  .hv2-hero h1{font-family:'Newsreader',serif;font-size:42px;font-weight:500;line-height:1.15;margin:0 0 18px;}
  .hv2-hero .hv2-sub{font-size:16px;line-height:1.6;color:${mkCharcoalSoft};max-width:520px;margin:0 auto 24px;}
  .hv2-benefit-row{display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin:0 auto 28px;max-width:560px;}
  .hv2-benefit-pill{font-size:12.5px;color:${mkCharcoalSoft};border:1px solid ${mkLine};border-radius:999px;padding:6px 14px;background:${mkCard};}
  .hv2-blob-wrap{position:relative;width:180px;height:180px;margin:8px auto 28px;overflow:visible;}

  .mk-btn{background:${mkCharcoal};color:${mkCream};border:none;border-radius:999px;padding:13px 26px;font-size:14.5px;font-weight:500;cursor:pointer;font-family:'Inter',var(--font-inter),sans-serif;}
  .mk-eyebrow{font-size:12px;letter-spacing:0.12em;text-transform:uppercase;color:${mkCharcoalSoft};margin-bottom:10px;text-align:center;}
  .mk-microcopy{font-size:13px;color:${mkCharcoalSoft};text-align:center;margin:12px 0 0;}
  .mk-text-link{background:none;border:none;padding:0;font-size:13px;color:${mkCharcoalSoft};text-decoration:underline;text-underline-offset:3px;cursor:pointer;font-family:inherit;}

  .mk-card{background:${mkCard};border:1px solid ${mkLine};border-radius:16px;padding:22px;text-align:left;}
  .mk-card h3{font-size:15.5px;font-weight:600;margin:0 0 8px;color:${mkCharcoal};}
  .mk-card p{font-size:13.5px;line-height:1.6;color:${mkCharcoalSoft};margin:0;}

  .hv2-placeholder{border:1px dashed ${mkCharcoalSoft};border-radius:14px;padding:20px;text-align:center;color:${mkCharcoalSoft};font-size:13px;background:rgba(0,0,0,0.02);}

  .hv2-how-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;max-width:680px;margin:24px auto 0;}
  .hv2-step-mark{width:24px;height:24px;border-radius:50%;background:${mkCharcoal};color:${mkCream};display:flex;align-items:center;justify-content:center;font-size:12px;margin-bottom:10px;font-family:'Newsreader',serif;}

  .hv2-mid-cta{text-align:center;padding:8px 24px 8px;}

  .hv2-faq-item{border-bottom:1px solid ${mkLine};padding:16px 0;}
  .hv2-faq-item h3{font-size:14.5px;font-weight:600;margin:0 0 8px;color:${mkCharcoal};}
  .hv2-faq-item p{font-size:13.5px;line-height:1.6;color:${mkCharcoalSoft};margin:0 0 6px;}

  .hv2-final{text-align:center;padding:56px 24px 96px;}
  .hv2-final h2{font-family:'Newsreader',serif;font-size:26px;font-weight:500;margin:0 0 20px;}
  .hv2-final-link{display:block;margin-top:12px;font-size:13px;color:${mkCharcoal};text-decoration:underline;}

  .hv2-sticky-bar{display:none;}
  @media(max-width:768px){
    .hv2-sticky-bar{
      display:flex;justify-content:center;position:fixed;left:0;right:0;bottom:0;z-index:500;
      padding:10px 16px calc(10px + env(safe-area-inset-bottom, 0px));
      background:rgba(247,244,237,0.94);backdrop-filter:blur(10px);
      border-top:1px solid ${mkLine};
    }
    .hv2-sticky-bar .mk-btn{width:100%;max-width:360px;}
    body{padding-bottom:64px;}
    .hv2-hero h1{font-size:32px;}
    .hv2-how-steps{grid-template-columns:1fr;}
  }
`

const BLOB_VW = 220
const BLOB_VH = 220

function SingleHeroBlob() {
  const pathRef = useRef<SVGPathElement | null>(null)
  const wrapRef = useRef<HTMLDivElement>(null)
  const hue = useMemo(() => sharedUserCuratedHue(SHARED_USER_SEED, 0), [])
  const profile = useMemo(() => sharedBuildPointMotionProfile(sharedHashSeed('home-v2-hero-blob'), 9), [])

  // respectReducedMotion: true — opt-in added to lib/blobs.ts specifically
  // for this page (default off everywhere else, see that file's own
  // comment). Under prefers-reduced-motion the blob renders its static
  // initial shape and never re-registers the RAF task.
  useBlobAnimation(
    (t) => {
      pathRef.current?.setAttribute(
        'd',
        sharedGenerateAnimatedBlobPath(BLOB_VW / 2, BLOB_VH / 2, 82, profile, 0.3, t)
      )
    },
    [profile],
    wrapRef,
    { respectReducedMotion: true }
  )

  return (
    <div className="hv2-blob-wrap" ref={wrapRef}>
      <svg viewBox={`0 0 ${BLOB_VW} ${BLOB_VH}`} width="100%" height="100%" style={{ overflow: 'visible' }}>
        <defs>
          <filter id="hv2-blob-blur" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="14" />
          </filter>
          <radialGradient id="hv2-blob-grad" cx="45%" cy="40%" r="70%">
            {blobGradientStops(hue, true).map((s, i) => (
              <stop key={i} offset={s.offset} stopColor={s.color} stopOpacity={s.opacity} />
            ))}
          </radialGradient>
        </defs>
        <path
          ref={pathRef}
          fill="url(#hv2-blob-grad)"
          filter="url(#hv2-blob-blur)"
          d={sharedGenerateAnimatedBlobPath(BLOB_VW / 2, BLOB_VH / 2, 82, profile, 0.3, 0)}
        />
      </svg>
    </div>
  )
}

export default function HomeV2Client() {
  return (
    <>
      {/* dangerouslySetInnerHTML, not <style>{css}</style>: this page renders
          its real content on the very first paint (no ready-gate like
          LandingPageClient's `if (!ready) return <div .../>`), so this style
          tag actually goes through SSR/hydration comparison. A JSX text
          child gets HTML-entity-escaped server-side (single quotes ->
          &#x27;) but not client-side, which is a real mismatch since <style>
          is a raw-text element the browser never entity-decodes — confirmed
          by reproducing it, not assumed. dangerouslySetInnerHTML sets the
          same raw string on both sides, so there's nothing to mismatch. css
          is a static, developer-authored string, not user input. */}
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div style={{ background: mkCream, color: mkCharcoal, fontFamily: sans }}>

        {/* ── Section 1: Hero ──────────────────────────────────────────── */}
        <section className="hv2-hero">
          <SingleHeroBlob />
          <h1>Get to know yourself better.</h1>
          <p className="hv2-sub">
            See the patterns behind how you think, feel and act, and go deeper on how you work,
            connect and recharge, so your choices fit who you are.
          </p>
          <div className="hv2-benefit-row">
            {BENEFIT_ROW.map((b) => (
              <span key={b} className="hv2-benefit-pill">{b}</span>
            ))}
          </div>
          <CtaButton variant="hero" />
          <p className="mk-microcopy">No card needed. About 15 minutes.</p>
          <div style={{ marginTop: 14 }}>
            <ContinueLink />
          </div>

          {/* Output card — ledger section 3: current /report/sample content is
              hand-written and must not be presented as real output. Placeholder
              until a real generated reveal replaces it (Phase 4, separate task). */}
          <div className="hv2-placeholder" style={{ maxWidth: 420, margin: '32px auto 0' }}>
            [PLACEHOLDER: real generated sample pattern — /report/sample is hand-written
            (SampleReportClient.tsx:36-73) and must not be used as real output]
          </div>
        </section>

        {/* ── Section 2: Patterns, not a type ─────────────────────────────── */}
        <section className="hv2-section">
          <div className="hv2-wrap">
            <h2>Patterns, not a four-letter type.</h2>
            <p className="hv2-body">
              Bearing scores you across 30 facets of the Big Five model, so you see specific
              patterns instead of one label.
            </p>
            <p className="hv2-body">
              Journaling and chat tools mostly reflect back what you put in. Bearing starts from
              the same 120 statements for everyone, in random order, before anything is interpreted.
            </p>
          </div>
        </section>

        {/* ── Section 3: The science ──────────────────────────────────────── */}
        <section className="hv2-section">
          <div className="hv2-wrap">
            <h2>Built on the IPIP-NEO-120.</h2>
            <p className="hv2-body">
              A public-domain Big Five inventory from published research (Johnson, 2014).
              Bearing&apos;s written explanations of your patterns are built on top of it.
            </p>
          </div>
        </section>

        {/* Mid-page CTA — ledger section 5 requires hero/mid-page/final band/sticky;
            placed here, roughly the page's midpoint (after section 3 of 5). */}
        <div className="hv2-mid-cta">
          <CtaButton variant="mid" />
        </div>

        {/* ── Section 4: How it works ─────────────────────────────────────── */}
        <section id="how-it-works" className="hv2-section">
          <div className="hv2-wrap">
            <h2>How it works</h2>
            <div className="hv2-how-steps">
              <div className="mk-card">
                <div className="hv2-step-mark">1</div>
                <h3>Answer naturally</h3>
                <p>Rate 120 short statements, like &lsquo;Worry about things.&rsquo;, from very inaccurate to very accurate.</p>
              </div>
              <div className="mk-card">
                <div className="hv2-step-mark">2</div>
                <h3>See your patterns early</h3>
                <p>See your first patterns while you&apos;re still answering. Most people get the first one before the halfway point.</p>
              </div>
              <div className="mk-card">
                <div className="hv2-step-mark">3</div>
                <h3>Unlock everything</h3>
                <p>Unlock everything for EUR 49, once: all 30 facets plus five deeper assessments (relationships, energy, working style, direction, environment). No subscription.</p>
              </div>
            </div>
          </div>
        </section>

        {/* ── Section 5: FAQ and final CTA ─────────────────────────────────── */}
        <section className="hv2-section">
          <div className="hv2-wrap">
            <h2>Questions</h2>
            {FAQ.map((item) => (
              <div className="hv2-faq-item" key={item.q}>
                <h3>{item.q}</h3>
                {item.a === null ? (
                  <div className="hv2-placeholder">[PLACEHOLDER: no drafted answer in the ledger yet]</div>
                ) : Array.isArray(item.a) ? (
                  item.a.map((line, i) => <p key={i}>{line}</p>)
                ) : (
                  <p>{item.a}</p>
                )}
              </div>
            ))}
          </div>
        </section>

        <div className="hv2-final">
          <h2>Start the assessment</h2>
          <CtaButton variant="final" />
          <Link href="/report/sample" className="hv2-final-link">
            See a sample report
          </Link>
        </div>

      </div>

      <div className="hv2-sticky-bar">
        <CtaButton variant="sticky" />
      </div>
    </>
  )
}
