'use client'

import Link from 'next/link'
import { useMemo, useRef } from 'react'
import {
  USER_SEED as SHARED_USER_SEED,
  hashSeed as sharedHashSeed,
  userCuratedHue as sharedUserCuratedHue,
  buildPointMotionProfile as sharedBuildPointMotionProfile,
  generateAnimatedBlobPath as sharedGenerateAnimatedBlobPath,
  blobGradientStops,
  useBlobAnimation,
} from '@/lib/blobs'
import CtaButton from './CtaButton'
import ContinueLink from './ContinueLink'
import FaqAccordion from './FaqAccordion'

// Phase 3b — reference/landing-redesign.md section 10, aligning the Phase 3
// skeleton with the approved reuse map (4b). Copy below is taken verbatim
// from the ledger. Anywhere the ledger has no concrete text (tagged U, or a
// question with no drafted answer, or the example card's caption fields)
// renders a visible [PLACEHOLDER: ...] instead of invented copy.

const sans = 'var(--font-inter), -apple-system, sans-serif'
const serif = 'var(--font-newsreader), Georgia, serif'

// Ledger section 6: "cream #F7F4ED, card tone #EFEAE0, charcoal #262420,
// charcoal-soft #57534A, line rgba(38,36,32,0.1) ... periwinkle and rose
// appear only in decorative blob and glow uses ... there is NO coral accent."
// mkPeriwinkle/mkRose are needed verbatim for the final CTA's glows (task 10);
// no other token exists here that isn't in this list.
const mkCream = '#F7F4ED'
const mkCard = '#EFEAE0'
const mkCharcoal = '#262420'
const mkCharcoalSoft = '#57534A'
const mkLine = 'rgba(38,36,32,0.1)'
const mkPeriwinkle = '#AEBBE8'
const mkRose = '#E9AFC0'

const BENEFIT_ROW = [
  'How you work',
  'How you connect',
  'What gives you energy',
  'Where you thrive',
  "Where you're headed",
]

const PROBLEM_LINES = [
  "You journal, meditate or talk it through, but it's hard to tell what to focus on.",
  'Reflecting on yourself tends to circle back to what you already believe about yourself.',
  'Many personality tests give you a label, and the results could describe almost anyone.',
]

const FAQ: { question: string; answer: string | string[] | null }[] = [
  { question: 'Is it accurate?', answer: null }, // ledger: "P, write carefully" — no drafted answer text given
  {
    question: 'Do I need an account?',
    answer: 'No, not for your first 5 patterns. You can optionally save progress with an email, and an account is needed at the paid unlock.',
  },
  { question: 'What does it cost?', answer: 'EUR 49 one time after the free 5 patterns.' },
  {
    question: 'What happens to my data?',
    answer: [
      'Your answers stay in your browser until you choose to save your progress or unlock.',
      "The written explanation of each pattern is generated by an AI model from the name of the trait, your result bucket (high, mid or low) and the trait word, not from your individual answers, and it is not sent your email.",
    ],
  },
  {
    question: 'Is this AI?',
    answer: 'Your scores come from the same fixed questionnaire for everyone. The explanation of each pattern is written by AI from your scores.',
  },
  { question: 'How is this different from 16Personalities or a chat with AI?', answer: null }, // ledger: "P, factual comparisons only" — no drafted answer text given
]

const css = `
  .hv2-wrap{max-width:720px;margin:0 auto;padding:0 24px;}
  /* Phase 3d: measured the live page's actual inter-section rhythm via
     bounding boxes (BASE_URL=https://getbearing.me) rather than reusing
     .hero's number for every generic content section — .hero is uniquely
     large (nav clearance + hero content) and applying its 88/70 to every
     .hv2-section produced gaps between 36px and 206px, far more uneven than
     the live page's own ~100-145px range. 20px/90px is copied verbatim from
     two real live sections that both use exactly this value (.usp-section
     and .demo-wrap), landing at a 110px gap when two such sections are
     adjacent — squarely inside the live page's measured range. .hero itself
     is unchanged (see .hv2-hero below), per this task's own instruction. */
  .hv2-section{padding:20px 32px 90px;}
  .hv2-section h2{font-family:'Newsreader',serif;font-size:28px;font-weight:500;line-height:1.25;margin:0 0 14px;text-align:center;}
  .hv2-body{font-size:15.5px;line-height:1.65;color:${mkCharcoalSoft};max-width:600px;margin:0 auto 14px;text-align:center;}

  .hv2-hero{padding:88px 32px 70px;text-align:center;}
  .hv2-hero h1{font-family:'Newsreader',serif;font-size:42px;font-weight:500;line-height:1.15;margin:0 0 18px;}
  .hv2-hero .hv2-sub{font-size:16px;line-height:1.6;color:${mkCharcoalSoft};max-width:520px;margin:0 auto 24px;}
  .hv2-benefit-row{display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin:0 auto 28px;max-width:560px;}
  /* Task 3: .badge-pill's radius (999px) and padding (5px 12px) kept; fill/
     border/text recolored for a light (cream) context — .badge-pill itself
     is styled for the dark .bento-card.dark it sits on (translucent white-
     on-dark), which would be invisible here. Font size 13px matches
     .mk-microcopy/.branch-flow's existing size, not a new value. */
  .hv2-benefit-pill{font-size:13px;color:${mkCharcoalSoft};border:1px solid ${mkLine};border-radius:999px;padding:5px 12px;background:${mkCard};}
  .hv2-blob-wrap{position:relative;width:180px;height:180px;margin:8px auto 28px;overflow:visible;}

  .mk-btn{background:${mkCharcoal};color:${mkCream};border:none;border-radius:999px;padding:13px 26px;font-size:14.5px;font-weight:500;cursor:pointer;font-family:'Inter',var(--font-inter),sans-serif;}
  .mk-eyebrow{font-size:12px;letter-spacing:0.12em;text-transform:uppercase;color:${mkCharcoalSoft};margin-bottom:10px;text-align:center;}
  .mk-microcopy{font-size:13px;color:${mkCharcoalSoft};text-align:center;margin:12px 0 0;}
  .mk-text-link{background:none;border:none;padding:0;font-size:13px;color:${mkCharcoalSoft};text-decoration:underline;text-underline-offset:3px;cursor:pointer;font-family:inherit;}

  /* Copied verbatim from LandingPageClient.tsx:51-53 (Problem section, task 6) */
  .section-head{max-width:600px;margin:0 auto 48px;text-align:center;}
  .section-head p{font-size:15px;color:${mkCharcoalSoft};line-height:1.6;margin:0;}

  .mk-card{background:${mkCard};border:1px solid ${mkLine};border-radius:16px;padding:22px;text-align:left;}
  .mk-card h3{font-size:15.5px;font-weight:600;margin:0 0 8px;color:${mkCharcoal};}
  .mk-card p{font-size:13.5px;line-height:1.6;color:${mkCharcoalSoft};margin:0;}

  .hv2-placeholder{border:1px dashed ${mkCharcoalSoft};border-radius:14px;padding:20px;text-align:center;color:${mkCharcoalSoft};font-size:13px;background:rgba(0,0,0,0.02);}
  .hv2-tile{text-align:center;}
  .hv2-tile h3{font-size:26px;}
  .hv2-tile p{margin-top:4px;}

  /* Number tiles + How it works steps — .how-steps/.step/.step-mark copied
     verbatim from LandingPageClient.tsx:112-114 (task 7 and 8) */
  .how-steps{max-width:1000px;margin:24px auto 0;display:grid;grid-template-columns:repeat(3,1fr);gap:24px;}
  .step{border:1px solid ${mkLine};border-radius:18px;padding:26px 22px;background:${mkCard};text-align:left;}
  .step-mark{width:28px;height:28px;border-radius:50%;background:${mkCharcoal};color:${mkCream};display:flex;align-items:center;justify-content:center;font-size:12px;margin-bottom:16px;font-family:'Newsreader',serif;}
  .step h3{font-size:16px;font-weight:600;margin:0 0 8px;}
  .step p{font-size:13.5px;line-height:1.55;color:${mkCharcoalSoft};margin:0;}

  /* Example pattern card — .app-card/.reveal-* copied verbatim from
     LandingPageClient.tsx:102,104,107-108 (task 5). .progress-trace
     (:103, held the retired "28 responses" line) is not copied — that line
     is dropped, not replaced, so there's nothing to render it. */
  .app-card{background:${mkCard};color:${mkCharcoal};border:1px solid ${mkLine};border-radius:22px;box-shadow:0 20px 40px -20px rgba(38,36,32,0.12);max-width:380px;margin:0 auto 24px;padding:44px 36px;text-align:center;}
  .reveal-eyebrow{font-size:10.5px;letter-spacing:0.1em;text-transform:uppercase;color:${mkCharcoalSoft};font-weight:600;margin:0 0 8px;}
  .reveal-line{font-family:'Newsreader',serif;font-style:italic;font-size:14px;line-height:1.55;color:${mkCharcoal};margin:0 0 16px;}
  .reveal-sub{font-size:12px;color:${mkCharcoalSoft};margin:0;}

  /* Static 5-dot scale (task 8) — rebuilt locally with mk* tokens per design
     rule 6 ("not tailwind.config tokens"); QuestionCard's DotScale uses
     Tailwind classes/colors and is not exported, and the assessment files
     are not to be touched. Size/thickness/gaps matched to
     QuestionCard.tsx:103-141: dots w-5 h-5 = 20px (:124), connecting line
     h-px = 1px inset left/right-[10px] i.e. half the dot width (:116),
     row-to-labels gap-4 = 16px (:113), label text-[11px] (:136-137). Colors
     are mk* tokens, not QuestionCard's Tailwind colors (#262420/#F7F4ED/
     #8C8A83) — task 3 asked to match size/thickness/gaps, not recolor. */
  .hv2-dotscale{display:flex;flex-direction:column;gap:16px;max-width:220px;margin:16px auto 0;}
  .hv2-dotscale-row{position:relative;display:flex;align-items:center;justify-content:space-between;}
  .hv2-dotscale-line{position:absolute;left:10px;right:10px;top:50%;transform:translateY(-50%);height:1px;background:${mkLine};}
  .hv2-dotscale-dot{position:relative;z-index:1;width:20px;height:20px;border-radius:50%;background:${mkCream};border:2px solid ${mkCharcoalSoft};}
  .hv2-dotscale-labels{display:flex;justify-content:space-between;font-size:11px;color:${mkCharcoalSoft};}

  .hv2-mid-cta{text-align:center;padding:8px 24px 8px;}

  /* FAQ accordion (task 9) — technique copied from DirectionAccordion.tsx:
     57-71 (max-height transition, rotating icon), landing mk* tokens.
     Padding 26px 22px matches .step's existing card padding
     (LandingPageClient.tsx:113) — the closest existing "card" padding value
     on the landing page, per task 3. */
  .hv2-faq-item{border-bottom:1px solid ${mkLine};padding:26px 22px;cursor:pointer;}
  .hv2-faq-row{display:flex;justify-content:space-between;align-items:center;gap:12px;min-height:44px;}
  .hv2-faq-item h3{font-size:14.5px;font-weight:600;margin:0;color:${mkCharcoal};}
  .hv2-faq-icon{font-size:18px;color:${mkCharcoalSoft};transition:transform 0.25s ease;flex-shrink:0;}
  .hv2-faq-body{max-height:0;overflow:hidden;transition:max-height 0.35s ease;}
  .hv2-faq-body-inner{padding-top:10px;}
  .hv2-faq-body-inner p{font-size:13.5px;line-height:1.6;color:${mkCharcoalSoft};margin:0 0 6px;}

  /* Final CTA — .final-outer/.final-card/.final-glow/.final-content/
     .final-cta-row/.final-link copied verbatim from LandingPageClient.tsx:
     119-127 (task 10). Colors, radii and glows unchanged. */
  .final-outer{background:${mkCharcoal};padding:90px 32px;}
  .final-card{max-width:900px;margin:0 auto;border-radius:32px;padding:80px 60px;text-align:center;position:relative;overflow:hidden;background:${mkCream};}
  .final-glow{position:absolute;border-radius:50%;filter:blur(60px);opacity:0.55;z-index:0;}
  .final-content{position:relative;z-index:1;}
  .final-card h2{font-family:'Newsreader',serif;font-size:38px;font-weight:500;max-width:560px;margin:0 auto 18px;line-height:1.2;}
  .final-cta-row{display:flex;justify-content:center;gap:24px;flex-wrap:wrap;align-items:center;margin-bottom:16px;}
  .final-link{color:${mkCharcoal};font-size:14px;text-decoration:underline;align-self:center;}

  /* Sticky bar (task 2) — solid mkCream + top border, matching
     app/report/page.tsx:60-64's .report-sticky-bar exactly (no translucency,
     no blur). Safe-area padding kept. */
  .hv2-sticky-bar{display:none;}
  @media(max-width:768px){
    .hv2-sticky-bar{
      display:flex;justify-content:center;position:fixed;left:0;right:0;bottom:0;z-index:500;
      padding:10px 16px calc(10px + env(safe-area-inset-bottom, 0px));
      background:${mkCream};
      border-top:1px solid ${mkLine};
    }
    .hv2-sticky-bar .mk-btn{width:100%;max-width:360px;}
    body{padding-bottom:64px;}
    /* .hv2-hero: verbatim from .hero's mobile override (LandingPageClient.tsx
       :151). .hv2-section: verbatim from .usp-section's real mobile value
       (:154, 10px 0 60px) — same measured-rhythm reasoning as the desktop
       rule above (Phase 3d), horizontal kept at 20px to match the hero. */
    .hv2-hero{padding:88px 20px 40px;}
    .hv2-section{padding:10px 20px 60px;}
    .hv2-hero h1{font-size:32px;}
    .how-steps{grid-template-columns:1fr;}
    .final-card{padding:56px 28px;}
  }
`

const BLOB_VW = 220
const BLOB_VH = 220

function SingleHeroBlob() {
  const pathRef = useRef<SVGPathElement | null>(null)
  const wrapRef = useRef<HTMLDivElement>(null)
  const hue = useMemo(() => sharedUserCuratedHue(SHARED_USER_SEED, 0), [])
  const profile = useMemo(() => sharedBuildPointMotionProfile(sharedHashSeed('home-v2-hero-blob'), 9), [])

  // respectReducedMotion: true — the one animated blob moment (design rule
  // 6). Under prefers-reduced-motion it renders its static initial shape and
  // never registers the RAF task.
  useBlobAnimation(
    (t) => {
      pathRef.current?.setAttribute(
        'd',
        sharedGenerateAnimatedBlobPath(BLOB_VW / 2, BLOB_VH / 2, 82, profile, 0.3, t)
      )
    },
    [profile],
    wrapRef,
    { respectReducedMotion: true }
  )

  return (
    <div className="hv2-blob-wrap" ref={wrapRef}>
      <svg viewBox={`0 0 ${BLOB_VW} ${BLOB_VH}`} width="100%" height="100%" style={{ overflow: 'visible' }}>
        <defs>
          <filter id="hv2-blob-blur" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="14" />
          </filter>
          <radialGradient id="hv2-blob-grad" cx="45%" cy="40%" r="70%">
            {blobGradientStops(hue, true).map((s, i) => (
              <stop key={i} offset={s.offset} stopColor={s.color} stopOpacity={s.opacity} />
            ))}
          </radialGradient>
        </defs>
        <path
          ref={pathRef}
          fill="url(#hv2-blob-grad)"
          filter="url(#hv2-blob-blur)"
          d={sharedGenerateAnimatedBlobPath(BLOB_VW / 2, BLOB_VH / 2, 82, profile, 0.3, 0)}
        />
      </svg>
    </div>
  )
}

// Example pattern card's blob — same rendering (viewBox, radius, gradient,
// ring) as LandingPageClient.tsx:425-471's DemoBlob, but rendered once and
// never animated. Design rule 6 says "exactly one animated blob moment
// (hero); everything else is static" — DemoBlob itself calls
// useBlobAnimation, so reusing it unmodified would create a second animated
// blob. This keeps DemoBlob's visual appearance verbatim while resolving
// that conflict in favor of the explicit "exactly one" rule. Flagged in the
// Phase 3b report as a judgment call, not literal ledger text.
function ExamplePatternBlob({ word }: { word: string }) {
  const hue = useMemo(() => sharedUserCuratedHue(SHARED_USER_SEED, 0), [])
  const profile = useMemo(() => sharedBuildPointMotionProfile(sharedHashSeed(`${word}-shape`), 9), [])
  const d = sharedGenerateAnimatedBlobPath(110, 110, 78, profile, 0.3, 0)

  return (
    <div style={{ width: 190, height: 170, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '16px auto 22px', position: 'relative' }}>
      <div style={{
        position: 'absolute', inset: 6, borderRadius: '50%',
        border: '1px solid hsl(8,50%,65%)', opacity: 0.5,
      }} />
      <svg viewBox="0 0 220 220" width="220" height="220" style={{ overflow: 'visible' }}>
        <defs>
          <filter id="example-blob-blur" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="9" />
          </filter>
          <radialGradient id="example-blob-grad" cx="45%" cy="40%" r="70%">
            {blobGradientStops(hue, true).map((s, i) => (
              <stop key={i} offset={s.offset} stopColor={s.color} stopOpacity={s.opacity} />
            ))}
          </radialGradient>
        </defs>
        <path fill="url(#example-blob-grad)" filter="url(#example-blob-blur)" d={d} />
      </svg>
      <span style={{
        position: 'absolute', left: '50%', top: '50%', transform: 'translate(-50%,-50%)',
        zIndex: 5, pointerEvents: 'none', whiteSpace: 'nowrap',
        fontFamily: serif, fontStyle: 'italic', fontWeight: 600, fontSize: 30,
        color: `hsl(${hue},45%,24%)`,
      }}>
        {word}
      </span>
    </div>
  )
}

// Small static 5-dot scale for How it works step 1 — rebuilt locally, not
// imported (QuestionCard.tsx's DotScale is not exported; the assessment
// files stay untouched). Landing mk* tokens, not QuestionCard's Tailwind
// colors. All 5 dots render unselected — showing the scale itself, not a
// specific (fabricated) answer.
function StaticDotScale() {
  return (
    <div className="hv2-dotscale">
      <div className="hv2-dotscale-row">
        <div className="hv2-dotscale-line" />
        {[1, 2, 3, 4, 5].map((n) => (
          <div key={n} className="hv2-dotscale-dot" />
        ))}
      </div>
      <div className="hv2-dotscale-labels">
        <span>Very Inaccurate</span>
        <span>Very Accurate</span>
      </div>
    </div>
  )
}

export default function HomeV2Client() {
  return (
    <>
      {/* dangerouslySetInnerHTML, not <style>{css}</style>: this page renders
          its real content on the very first paint (no ready-gate like
          LandingPageClient's `if (!ready) return <div .../>`), so this style
          tag actually goes through SSR/hydration comparison. A JSX text
          child gets HTML-entity-escaped server-side but not client-side,
          which is a real mismatch since <style> is a raw-text element the
          browser never entity-decodes — confirmed by reproducing it, not
          assumed. dangerouslySetInnerHTML sets the same raw string on both
          sides, so there's nothing to mismatch. css is a static,
          developer-authored string, not user input. */}
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div style={{ background: mkCream, color: mkCharcoal, fontFamily: sans }}>

        {/* ── Section 1: Hero ──────────────────────────────────────────── */}
        <section className="hv2-hero" data-testid="section-hero">
          <SingleHeroBlob />
          <h1>Get to know yourself better.</h1>
          <p className="hv2-sub">
            See the patterns behind how you think, feel and act, and go deeper on how you work,
            connect and recharge, so your choices fit who you are.
          </p>
          <div className="hv2-benefit-row">
            {BENEFIT_ROW.map((b) => (
              <span key={b} className="hv2-benefit-pill">{b}</span>
            ))}
          </div>
          <CtaButton variant="hero" />
          <p className="mk-microcopy">
            Rate 120 short statements. Your first 5 patterns are free, no account needed. About 15 minutes.
          </p>
          <div style={{ marginTop: 14 }}>
            <ContinueLink />
          </div>

          {/* Example pattern card (task 5) */}
          <div className="app-card" style={{ marginTop: 32 }}>
            <p className="reveal-eyebrow">Example pattern</p>
            <ExamplePatternBlob word="Deliberate" />
            <p className="reveal-line">[PLACEHOLDER: trait quote — awaiting approved copy]</p>
            <p className="reveal-sub">[PLACEHOLDER: supporting line — awaiting approved copy]</p>
          </div>
          {/* AI line, verbatim from the ledger (section 3, task 4) — placed
              under the example card, not inside it. */}
          <p className="mk-microcopy">
            The written explanation of each pattern is generated by AI from your results.
          </p>
        </section>

        {/* ── Section 1b: Problem (task 6) ─────────────────────────────────── */}
        <section className="hv2-section" data-testid="section-problem">
          <div className="section-head">
            <div className="mk-eyebrow">Sound familiar?</div>
            {PROBLEM_LINES.map((line) => (
              <p key={line}>{line}</p>
            ))}
          </div>
        </section>

        {/* ── Section: Why it's different (sections 2+3 merged, task 7) ────── */}
        <section className="hv2-section" data-testid="section-why-different">
          <div className="hv2-wrap">
            <h2>Patterns, not a four-letter type.</h2>
            <p className="hv2-body">
              Bearing scores you across 30 facets of the Big Five model, so you see specific
              patterns instead of one label.
            </p>
            <p className="hv2-body">
              Journaling and chat tools mostly reflect back what you put in. Bearing starts from
              the same 120 statements for everyone, in random order, before anything is interpreted.
            </p>
            {/* Number tiles — three parallel facts, not steps (ledger line
                145: "Do not number them 1, 2, 3"). No .step-mark. */}
            <div className="how-steps">
              <div className="step hv2-tile">
                <h3>120</h3>
                <p>statements</p>
              </div>
              <div className="step hv2-tile">
                <h3>30</h3>
                <p>facets</p>
              </div>
              <div className="step hv2-tile">
                <h3>about 15</h3>
                <p>minutes</p>
              </div>
            </div>
            <p className="mk-microcopy" style={{ marginTop: 24 }}>
              Built on the IPIP-NEO-120, a public-domain Big Five inventory from published research (Johnson, 2014).
            </p>
          </div>
        </section>

        {/* Mid-page CTA */}
        <div className="hv2-mid-cta">
          <CtaButton variant="mid" />
        </div>

        {/* ── Section: How it works (task 8) ───────────────────────────────── */}
        <section id="how-it-works" className="hv2-section" data-testid="section-how-it-works">
          <div className="hv2-wrap">
            <h2>How it works</h2>
            <div className="how-steps">
              <div className="step">
                <div className="step-mark">1</div>
                <h3>Answer naturally</h3>
                <p>Rate 120 short statements, like &lsquo;Worry about things.&rsquo;, from very inaccurate to very accurate.</p>
                <StaticDotScale />
              </div>
              <div className="step">
                <div className="step-mark">2</div>
                <h3>See your patterns early</h3>
                <p>See your first patterns while you&apos;re still answering. Most people get the first one before the halfway point.</p>
              </div>
              <div className="step">
                <div className="step-mark">3</div>
                <h3>Unlock everything</h3>
                <p>Unlock everything for EUR 49, once: all 30 facets plus five deeper assessments (relationships, energy, working style, direction, environment). No subscription.</p>
              </div>
            </div>
          </div>
        </section>

        {/* ── Section 5: FAQ and final CTA (task 9) ─────────────────────────── */}
        <section className="hv2-section" data-testid="section-faq">
          <div className="hv2-wrap">
            <h2>Questions</h2>
            <FaqAccordion items={FAQ} />
          </div>
        </section>

        {/* ── Final CTA (task 10) ──────────────────────────────────────────── */}
        <section className="final-outer">
          <div className="final-card">
            <div className="final-glow" style={{ width: 280, height: 280, background: mkPeriwinkle, top: -80, left: -80 }} />
            <div className="final-glow" style={{ width: 260, height: 260, background: mkRose, bottom: -90, right: -70 }} />
            <div className="final-content">
              <h2>Start the assessment</h2>
              <div className="final-cta-row">
                <CtaButton variant="final" />
              </div>
              <Link href="/report/sample" className="final-link">
                See a sample report
              </Link>
            </div>
          </div>
        </section>

      </div>

      <div className="hv2-sticky-bar">
        <CtaButton variant="sticky" />
      </div>
    </>
  )
}
